version: '3.8'

services:
  # Backend Flask API
  backend:
    build: ./backend
    container_name: splitfree-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - ./backend:/app
      - /app/__pycache__
    networks:
      - splitfree-network

  # Frontend React App
  frontend:
    build: ./frontend
    container_name: splitfree-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://backend:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - splitfree-network

networks:
  splitfree-network:
    driver: bridge