"""empty message

Revision ID: 30563fdcce59
Revises: 5b24d8c5627e
Create Date: 2025-10-18 22:56:38.397358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30563fdcce59'
down_revision = '5b24d8c5627e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('split_type', sa.String(length=20), nullable=False))

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.alter_column('invite_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['invite_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('invite_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('split_type')

    # ### end Alembic commands ###
