"""add invite_code and is_public to groups

Revision ID: 4898462826a4
Revises: b935078c58dc
Create Date: 2025-10-06 08:42:22.689952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4898462826a4'
down_revision = 'b935078c58dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('invite_token', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_token')
    )
    
    # Add columns with nullable=True first
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))
    
    # Update existing rows with default values
    import random
    import string
    from sqlalchemy import text
    
    connection = op.get_bind()
    
    # Get all existing groups
    result = connection.execute(text("SELECT id FROM groups"))
    group_ids = [row[0] for row in result]
    
    # Generate unique invite codes for existing groups
    used_codes = set()
    for group_id in group_ids:
        # Generate unique invite code
        while True:
            letters = ''.join(random.choices(string.ascii_uppercase, k=3))
            numbers = ''.join(random.choices(string.digits, k=3))
            code = f"SPLIT-{letters}{numbers}"
            if code not in used_codes:
                used_codes.add(code)
                break
        
        # Update the group with invite code and set as public by default
        connection.execute(
            text("UPDATE groups SET invite_code = :code, is_public = true WHERE id = :id"),
            {"code": code, "id": group_id}
        )
    
    # Now make the columns NOT NULL and add constraints
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.alter_column('invite_code', nullable=False)
        batch_op.alter_column('is_public', nullable=False)
        batch_op.create_unique_constraint(None, ['invite_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('is_public')
        batch_op.drop_column('invite_code')

    op.drop_table('group_invitations')
    # ### end Alembic commands ###
