"""empty message

Revision ID: fac83809dbc4
Revises: 
Create Date: 2025-09-21 22:58:46.487290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fac83809dbc4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Add email column as nullable first
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
    
    # Update existing users with a default email if any exist
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE users 
        SET email = username || '@example.com' 
        WHERE email IS NULL
    """))
    
    # Now make the column NOT NULL and add unique constraint
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email', nullable=False)
        batch_op.create_unique_constraint('uq_users_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_email', type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
