name: Docker Image CI

on:
  push:
    branches:
      - main
    paths: 
      - backend/Dockerfile
      - frontend/Dockerfile
      - 'docker-compose*'
      
  workflow_dispatch:

jobs:
  
  build-backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build backend image
      run: docker build ./backend -f Dockerfile --tag backend-image:$(date +%s)
      
  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build frontend image
      run: docker build ./frontend -f Dockerfile --tag frontend-image:$(date +%s)
